<?php
/**
 * Copyright (C) Marcelle Hövelmanns, art solution - All Rights Reserved
 *
 * @file        ProductModel.php
 * @author      Marcelle Hövelmanns
 * @site        http://www.artsolution.de
 * @date        23.10.17
 */

namespace Affilicon;


class Product extends AbstractModel
{
  protected $resource;
  protected $HttpService;
  protected $Client;

  public function __construct()
  {
    parent::__construct();
    $this->resource = API['routes']['products'];
  }

  public function findById($id)
  {
    parent::findById($id); // TODO: Change the autogenerated stub
  }

  public function find($params, $with)
  {
    parent::find($params, $with); // TODO: Change the autogenerated stub
  }

}