<?php

/**
 * Copyright (C) Marcelle Hövelmanns, art solution - All Rights Reserved
 *
 * @file        Client.php
 * @author      Marcelle Hövelmanns
 * @site        http://www.artsolution.de
 * @date        02.10.17
 */

namespace Affilicon;

/**
 * Class ApiClient
 * @package Affilicon
 */

class Client extends AbstractClient implements ClientInterface
{
  protected $token;
  protected $username;
  protected $password;
  public $clientId;
  public $countryId;
  public $userLanguage;
  public static $instance;

  /** @var  HttpService */
  protected $HttpService;

  protected function __construct()
  {
    parent::__construct();
  }

  public static function getInstance()
  {
    return parent::getInstance(); // TODO: Change the autogenerated stub
  }

  public function init()
  {
    return parent::init(); // TODO: Change the autogenerated stub
  }

  public function isAuthenticated()
  {
    return parent::isAuthenticated(); // TODO: Change the autogenerated stub
  }

  public function authenticate()
  {
    return parent::authenticate(); // TODO: Change the autogenerated stub
  }

  public function setUserName($username)
  {
    return parent::setUserName($username); // TODO: Change the autogenerated stub
  }

  public function getUsername()
  {
    return parent::getUsername(); // TODO: Change the autogenerated stub
  }

  public function setPassword($password)
  {
    return parent::setPassword($password); // TODO: Change the autogenerated stub
  }

  public function getToken()
  {
    return parent::getToken(); // TODO: Change the autogenerated stub
  }

  public function setClientId($id)
  {
    return parent::setClientId($id); // TODO: Change the autogenerated stub
  }

  public function getClientId()
  {
    return parent::getClientId(); // TODO: Change the autogenerated stub
  }

  public function getCountryId()
  {
    return parent::getCountryId(); // TODO: Change the autogenerated stub
  }

  public function setCountryId($countryId)
  {
    return parent::setCountryId($countryId); // TODO: Change the autogenerated stub
  }

  public function getUserLanguage()
  {
    return parent::getUserLanguage(); // TODO: Change the autogenerated stub
  }

  public function setUserLanguage($userLanguage)
  {
    return parent::setUserLanguage($userLanguage); // TODO: Change the autogenerated stub
  }


}